name: 'DeepSourceCorp Globstar Action'
description: 'Setup DeepSourceCorp/globstar in GitHub Action environment'
author: 'Ayushman Chhabra'
inputs:
  version:
    description: 'Version to download'
    required: true
    default: 'latest'
  auth-token:
    description: 'Auth token to use for downloading the version'
    required: true
    default: ${{ github.token }}
  cache:
    description: 'Enable or disable caching of Globstar binary'
    required: true
    default: false
runs:
  using: node20
  main: 'dist/index.js'
