name: 'DeepSourceCorp Globstar Action'
description: 'Setup DeepSourceCorp/globstar in GitHub Action environment'
author: 'Ayushman Chhabra'
inputs:
  version:
    description: 'Version to download'
    required: true
    default: 'latest'
outputs:
  version:
    description: 'Version to download'
runs:
  using: 'node20'
  main: 'index.js'
