name: 'DeepSourceCorp Globstar Action'
description: 'Setup DeepSourceCorp/globstar in GitHub Action environment'
author: 'Ayushman Chhabra'
inputs:
  version:
    description: 'Version to download'
    required: true
    default: 'latest'
runs:
  using: 'node20'
  main: 'dist/index.js'
