name: ci

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup Globstar
        uses: ayushmanchhabra/globstar-action@download
        with:
          version: "latest"
