name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-2024

    steps:
      - name: Setup Globstar
      uses: ayushmanchhabra/globstar@v0.0.0
        with:
          version: 'latest'
