name: ci

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build action
        run: npm run dist

      - name: Setup Globstar
        uses: ayushmanchhabra/globstar-action@main
        with:
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest"
